services:
  nodered:
    build: ./nodered
    ports:
      - 1880:1880
    volumes:
      - ./nodered/data:/data
    container_name: nodered
    networks:
      - service_network
  mosquitto:
    build: ./mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    container_name: mosquitto
    networks:
      - service_network
  nodejs:
    build: ./nodejs
    ports:
      - 3002:3002
    volumes:
      - ./nodejs/uploads/:/home/node/uploads/
    container_name: nodejs
    networks:
      - service_network

networks:
  service_network:
    # Specify driver options
    driver: bridge